### ISSUE TITLE
[Feat] Core 모듈 기본 셋팅

### ISSUE THREAD

**Issue by ham2174** [ASAP-Side/aljo-android#13]
## ISSUE
코어 모듈에 remote, local, ui 모듈을 생성합니다.
remote 모듈에서 네트워크 기본 셋팅을 진행합니다.
local 모듈에서 data store, data base 기본 셋팅을 진행합니다.

## To-Do
- [x] : remote 모듈 생성
- [x] : 네트워크 셋팅
- [x] : local 모듈 생성
- [x] : data store 셋팅
- [x] : data base 셋팅
- [x] : ui 모듈 생성

**Comment by ham2174** [comment]
## ISSUE
EncryptedSharedPreferences → Jetpack Datastore 로 마이그레이션
- 관련 PR : #16 

## To-Do
- [x] : Datastore 마이그레이션
